#!/usr/bin/env python3
"""Generate crates/cofdmtv-core/src/coding/tables.rs from the aicodix C++ headers.

The frozen-bit tables of the polar codes and the 8x11 pixel font of the "fancy header"
come verbatim from the original sources (cloned into reference/, see
tools/cxx-reference/build.sh), so that COFDMtv's codes match the originals bit for bit:

  reference/assempix/app/src/main/cpp/polar_tables.hh    COFDMTV image modes 6..13
  reference/rattlegram/app/src/main/cpp/polar_tables.hh  COFDMTV text modes 14..16
  reference/modem/polar_tables.hh                        aicodix modem (datagrams)
  reference/shredpix/app/src/main/cpp/base37_bitmap.hh   fancy header font

usage: python tools/gen_tables.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REF = ROOT / "reference"
OUT = ROOT / "crates" / "cofdmtv-core" / "src" / "coding" / "tables.rs"

SOURCES = [
    ("IMAGE", REF / "assempix/app/src/main/cpp/polar_tables.hh", "COFDMTV image modes 6..13 (Assempix/Shredpix)"),
    ("TEXT", REF / "rattlegram/app/src/main/cpp/polar_tables.hh", "COFDMTV text modes 14..16 (Rattlegram)"),
    ("MODEM", REF / "modem/polar_tables.hh", "aicodix modem datagrams"),
]

ARRAY = re.compile(r"static const (uint32_t|uint8_t) (\w+)\[(\d+)\] = \{([^}]*)\};", re.S)


def arrays(path):
    text = path.read_text()
    for kind, name, size, body in ARRAY.findall(text):
        values = [int(v, 0) for v in body.replace("\n", " ").split(",") if v.strip()]
        assert len(values) == int(size), (path, name, len(values), size)
        yield kind, name, values


def rust_array(name, rust_type, values, per_line):
    hexw = 8 if rust_type == "u32" else 2
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        if rust_type == "u32":
            lines.append("    " + " ".join(f"0x{v:0{hexw}x}," for v in chunk))
        else:
            lines.append("    " + " ".join(f"{v}," for v in chunk))
    return f"pub static {name}: [{rust_type}; {len(values)}] = [\n" + "\n".join(lines) + "\n];\n"


def main():
    out = [
        "//! Constant tables from the original aicodix C++ sources (BSD Zero Clause License),",
        "//! generated by `tools/gen_tables.py`: do not edit by hand.",
        "//!",
        "//! `*_FROZEN_N_K` are the frozen-bit sets of the polar codes: bit `i` of word `i / 32`",
        "//! is set when bit `i` of the length-`N` code carries no information. `K` counts the",
        "//! information bits including the CRC.",
        "",
        "#![allow(clippy::unreadable_literal)]",
        "",
    ]
    for prefix, path, what in SOURCES:
        out.append(f"// ---- {what}: {path.relative_to(ROOT).as_posix()}")
        out.append("")
        for kind, name, values in arrays(path):
            assert kind == "uint32_t"
            rust_name = prefix + "_" + name.upper()
            out.append(f"/// `{name}` of {what}.")
            out.append(rust_array(rust_name, "u32", values, 8))
    bitmap = REF / "shredpix/app/src/main/cpp/base37_bitmap.hh"
    ((_, _, font),) = list(arrays(bitmap))
    out.append(f"// ---- fancy header font: {bitmap.relative_to(ROOT).as_posix()}")
    out.append("")
    out.append("/// 8x11 pixel glyphs of the 37 base-37 characters (space, 0-9, A-Z), one row of")
    out.append("/// all 37 glyphs after the other (`[char + 37 * row]`, MSB = leftmost pixel); from the")
    out.append("/// Terminus font (SIL Open Font License).")
    out.append(rust_array("BASE37_BITMAP", "u8", font, 37))
    OUT.write_text("\n".join(out), newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
